apiVersion: skaffold/v2beta15
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: zakiafada32/sc-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: zakiafada32/sc-users
      context: users
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
deploy:
  kubectl:
    manifests:
      - ./k8s/*
