apiVersion: v1
kind: Service
metadata:
  name: auth-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: auth
  template:
    metadata:
      labels:
        component: auth
    spec:
      containers:
        - name: auth
          image: zakiafada32/sc-auth:1.1
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: 'mongodb://mongo-cluster-ip-service:27017/sejutacita'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-key-secret
                  key: JWT_KEY
            - name: JWT_REFRESH_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-refresh-secret
                  key: JWT_REFRESH_KEY
