apiVersion: v1
kind: Service
metadata:
  name: users-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: users
  ports:
    - name: users
      protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: users
  template:
    metadata:
      labels:
        component: users
    spec:
      containers:
        - name: users
          image: zakiafada32/sc-users:1.1
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URI
              value: 'mongodb://mongo-cluster-ip-service:27017/sejutacita'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-key-secret
                  key: JWT_KEY
            - name: JWT_REFRESH_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-refresh-secret
                  key: JWT_REFRESH_KEY
